[project]
name = "eavs"
version = "0"
description = "Election Administration and Voting Survey (EAVS) data cleaning"
authors = [
    { name = "Civic Tech DC" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.12.0"
dependencies = [
    "httpx",
    "loguru",
    "pandas",
    "python-calamine",
    "python-dotenv",
    "streamlit",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyterlab",
    "ruff",
]

[tool.ruff]
line-length = 100
target-version = "py312"
src = ["eavs/**/*.py"]

[tool.ruff.lint]
select = [
    "E", # Pyflakes
    "F", # Pycodestyle
    "I", # isort
]
unfixable = ["F"]

[tool.ruff.lint.isort]
known-first-party = ["eavs"]
force-sort-within-sections = true
